### ISSUE TITLE
Revisions to indices reference needed

### ISSUE THREAD

**Issue by clairbarnes** [UCL/UKCORDEX-plot-explorer-dev#59]
- r95ptot/r99ptot now calculated as exceedance during period of interest
- dtr added
- str added

**Comment by clairbarnes** [comment]
Also need to clarify that u & v wind components are provided wrt OSGB axes

**Comment by raquel-ucl** [comment]
@clairbarnes we were listing the issues in the prod repo, incase you want to keep all under the same list: https://github.com/UCL/UKCORDEX-plot-explorer/issues

**Comment by clairbarnes** [comment]
fwd is described as proportion of wet days: confirm whether this is correct, or whether it is standardised to number of wet days

**Comment by clairbarnes** [comment]
str/dtr added, r95ptot/r99ptot updated, comment on reference frame of u- and v-components added. No changes needed to fwd, which is computed as proportion of wet days.
